appName: ai-platform
version: v1

image:
  repository: 502759712845.dkr.ecr.us-east-1.amazonaws.com/ai-platform
  tag: sha-9939a88
  pullPolicy: Always

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: localhost

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: APP_ENV
    value: "development"
  - name: APP_LOG_LEVEL
    value: "debug"
  - name: LLM_BASE_URL
    value: "https://api.groq.com/openai/v1"
  - name: LLM_MODEL
    value: "llama-3.3-70b-versatile"
  - name: QDRANT_COLLECTION
    value: "faq_documents"
  - name: CACHE_TTL_SECONDS
    value: "3600"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://tempo.monitoring.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "ai-platform"
